name: upower
version: 0.1.0

description:
  Provides a client to connect to UPower - the service that does power management on Linux.

homepage: https://github.com/canonical/upower.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dbus: ^0.2.1

dev_dependencies:
  pedantic: ^1.9.0
